---
version: '3'

services:
  redis:
    image: redis:alpine
    ports:
     - 6379:6379

  fluent-bit-go-redis:
    tty: true
    depends_on:
      - redis
    image: docker.io/flozano/fluent-bit-go-redis-output
#    build:
#      context: .
#      dockerfile: Dockerfile
    volumes:
      - $PWD/test.log:/test.log
